// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// DriverLocationHandler is an autogenerated mock type for the DriverLocationHandler type
type DriverLocationHandler struct {
	mock.Mock
}

// Find provides a mock function with given fields: w, r
func (_m *DriverLocationHandler) Find(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UpsertBulk provides a mock function with given fields: w, r
func (_m *DriverLocationHandler) UpsertBulk(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
