// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

// Start provides a mock function with given fields: _a0
func (_m *Server) Start(_a0 context.Context) {
	_m.Called(_a0)
}
