// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/s3f4/locationmatcher/internal/driverlocation/repository"
	mock "github.com/stretchr/testify/mock"
)

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

// Start provides a mock function with given fields: _a0, _a1
func (_m *Server) Start(_a0 context.Context, _a1 repository.Repository) {
	_m.Called(_a0, _a1)
}
